// var x = 20;
// var y = 20;
// var xy = x+y;
// console.log(xy);
// var a = 20;
// var b = 20;
// var ab = a-b;
// console.log(typeof(ab));
// var nadim = "2000";
// console.log(parseInt(nadim));
// var c = "22.75";
// console.log(parseFloat(c));
// var rakim = 19;
// var safayet = 21;
// console.log(rakim+safayet);
